[bumpver]
current_version = "2.4.1"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "Bump version: {old_version} -> {new_version}"
tag_message = "v{new_version}"
tag_scope = "default"
commit = true
tag = false
push = false

[bumpver.file_patterns]
"setup.py" = [
    "{version}",
]
